---
- name: Download nebula
  ansible.builtin.get_url:
    url: "{{ nebula_download_url }}"
    dest: "{{ nebula_download_dir }}/nebula.tar.gz"
    mode: "0644"

- name: Unarchive nebula
  ansible.builtin.unarchive:
    src: "{{ nebula_download_dir }}/nebula.tar.gz"
    dest: "{{ nebula_bin_dir }}"
    remote_src: true

- name: Template nebula systemd unit
  ansible.builtin.template:
    src: nebula.service.j2
    dest: "/etc/systemd/system/{{ nebula_service_name }}.service"
    mode: "0644"
